package br.com.inovamobil.reader.dominio.entidade;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here

import java.io.Serializable;
// KEEP INCLUDES END
/**
 * Entity mapped to table ClienteServ.
 */
public class Servico implements Serializable {

    private Long IdentificadorInterface;
    private String Cli_Codigo;
    private Long Codigo;
    private String Descricao;
    private Long Tipo;
    private Long TipoAplicacao;
    private Long TipoValor;
    private Double ValorPercentualConsumo;
    private String ImprimeDiscriminado;
    private String VinculadoAguaEsgoto;
    private Double ValorCalculado;
    private String ConsideraServicoCalculoPercentualValorTotalFatura;
    private String ConsideraServicoCalculoEsgotoGrupoCalculo;
    private String CobraSomenteValorTotalFaturaMaiorZero;
    private String StringEspecial;
    private String ConsideraServicoCalculoValorTotalFatura;
    private String CobraServicoVinculadoQuandoAguaEsgotoZerados;
    private String NomeArquivoExportacao;
    private Double ValorMaximoAcrescimoDesconto;
    private String UtilizaDescontoParaCobrancaValorMinimoFatura;
    private Long TipoServicoImposto;
    private Long Identificador;
    private String ServicoAdicionadoRotinaCalculo;
    private Long ServicoSequencial;
    private String DesconsideraCobrancaQuandoConsumoMenorTarifaMinima;
    private Long ConsumoLimite;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Servico() {
    }

    public Servico(Long Identificador) {
        this.Identificador = Identificador;
    }

    public Servico(Long IdentificadorInterface, String Cli_Codigo, Long Codigo, String Descricao, Long Tipo, Long TipoAplicacao, Long TipoValor, Double ValorPercentualConsumo, String ImprimeDiscriminado, String VinculadoAguaEsgoto, Double ValorCalculado, String ConsideraServicoCalculoPercentualValorTotalFatura, String ConsideraServicoCalculoEsgotoGrupoCalculo, String CobraSomenteValorTotalFaturaMaiorZero, String StringEspecial, String ConsideraServicoCalculoValorTotalFatura, String CobraServicoVinculadoQuandoAguaEsgotoZerados, String NomeArquivoExportacao, Double ValorMaximoAcrescimoDesconto, String UtilizaDescontoParaCobrancaValorMinimoFatura, Long TipoServicoImposto, Long Identificador, String ServicoAdicionadoRotinaCalculo, Long ServicoSequencial, String DesconsideraCobrancaQuandoConsumoMenorTarifaMinima, Long ConsumoLimite) {
        this.IdentificadorInterface = IdentificadorInterface;
        this.Cli_Codigo = Cli_Codigo;
        this.Codigo = Codigo;
        this.Descricao = Descricao;
        this.Tipo = Tipo;
        this.TipoAplicacao = TipoAplicacao;
        this.TipoValor = TipoValor;
        this.ValorPercentualConsumo = ValorPercentualConsumo;
        this.ImprimeDiscriminado = ImprimeDiscriminado;
        this.VinculadoAguaEsgoto = VinculadoAguaEsgoto;
        this.ValorCalculado = ValorCalculado;
        this.ConsideraServicoCalculoPercentualValorTotalFatura = ConsideraServicoCalculoPercentualValorTotalFatura;
        this.ConsideraServicoCalculoEsgotoGrupoCalculo = ConsideraServicoCalculoEsgotoGrupoCalculo;
        this.CobraSomenteValorTotalFaturaMaiorZero = CobraSomenteValorTotalFaturaMaiorZero;
        this.StringEspecial = StringEspecial;
        this.ConsideraServicoCalculoValorTotalFatura = ConsideraServicoCalculoValorTotalFatura;
        this.CobraServicoVinculadoQuandoAguaEsgotoZerados = CobraServicoVinculadoQuandoAguaEsgotoZerados;
        this.NomeArquivoExportacao = NomeArquivoExportacao;
        this.ValorMaximoAcrescimoDesconto = ValorMaximoAcrescimoDesconto;
        this.UtilizaDescontoParaCobrancaValorMinimoFatura = UtilizaDescontoParaCobrancaValorMinimoFatura;
        this.TipoServicoImposto = TipoServicoImposto;
        this.Identificador = Identificador;
        this.ServicoAdicionadoRotinaCalculo = ServicoAdicionadoRotinaCalculo;
        this.ServicoSequencial = ServicoSequencial;
        this.DesconsideraCobrancaQuandoConsumoMenorTarifaMinima = DesconsideraCobrancaQuandoConsumoMenorTarifaMinima;
        this.ConsumoLimite = ConsumoLimite;
    }

    public Long getIdentificadorInterface() {
        return IdentificadorInterface;
    }

    public void setIdentificadorInterface(Long IdentificadorInterface) {
        this.IdentificadorInterface = IdentificadorInterface;
    }

    public String getCli_Codigo() {
        return Cli_Codigo;
    }

    public void setCli_Codigo(String Cli_Codigo) {
        this.Cli_Codigo = Cli_Codigo;
    }

    public Long getCodigo() {
        return Codigo;
    }

    public void setCodigo(Long Codigo) {
        this.Codigo = Codigo;
    }

    public String getDescricao() {
        return Descricao;
    }

    public void setDescricao(String Descricao) {
        this.Descricao = Descricao;
    }

    public Long getTipo() {
        return Tipo;
    }

    public void setTipo(Long Tipo) {
        this.Tipo = Tipo;
    }

    public Long getTipoAplicacao() {
        return TipoAplicacao;
    }

    public void setTipoAplicacao(Long TipoAplicacao) {
        this.TipoAplicacao = TipoAplicacao;
    }

    public Long getTipoValor() {
        return TipoValor;
    }

    public void setTipoValor(Long TipoValor) {
        this.TipoValor = TipoValor;
    }

    public Double getValorPercentualConsumo() {
        return ValorPercentualConsumo;
    }

    public void setValorPercentualConsumo(Double ValorPercentualConsumo) {
        this.ValorPercentualConsumo = ValorPercentualConsumo;
    }

    public String getImprimeDiscriminado() {
        return ImprimeDiscriminado;
    }

    public void setImprimeDiscriminado(String ImprimeDiscriminado) {
        this.ImprimeDiscriminado = ImprimeDiscriminado;
    }

    public String getVinculadoAguaEsgoto() {
        return VinculadoAguaEsgoto;
    }

    public void setVinculadoAguaEsgoto(String VinculadoAguaEsgoto) {
        this.VinculadoAguaEsgoto = VinculadoAguaEsgoto;
    }

    public Double getValorCalculado() {
        return ValorCalculado;
    }

    public void setValorCalculado(Double ValorCalculado) {
        this.ValorCalculado = ValorCalculado;
    }

    public String getConsideraServicoCalculoPercentualValorTotalFatura() {
        return ConsideraServicoCalculoPercentualValorTotalFatura;
    }

    public void setConsideraServicoCalculoPercentualValorTotalFatura(String ConsideraServicoCalculoPercentualValorTotalFatura) {
        this.ConsideraServicoCalculoPercentualValorTotalFatura = ConsideraServicoCalculoPercentualValorTotalFatura;
    }

    public String getConsideraServicoCalculoEsgotoGrupoCalculo() {
        return ConsideraServicoCalculoEsgotoGrupoCalculo;
    }

    public void setConsideraServicoCalculoEsgotoGrupoCalculo(String ConsideraServicoCalculoEsgotoGrupoCalculo) {
        this.ConsideraServicoCalculoEsgotoGrupoCalculo = ConsideraServicoCalculoEsgotoGrupoCalculo;
    }

    public String getCobraSomenteValorTotalFaturaMaiorZero() {
        return CobraSomenteValorTotalFaturaMaiorZero;
    }

    public void setCobraSomenteValorTotalFaturaMaiorZero(String CobraSomenteValorTotalFaturaMaiorZero) {
        this.CobraSomenteValorTotalFaturaMaiorZero = CobraSomenteValorTotalFaturaMaiorZero;
    }

    public String getStringEspecial() {
        return StringEspecial;
    }

    public void setStringEspecial(String StringEspecial) {
        this.StringEspecial = StringEspecial;
    }

    public String getConsideraServicoCalculoValorTotalFatura() {
        return ConsideraServicoCalculoValorTotalFatura;
    }

    public void setConsideraServicoCalculoValorTotalFatura(String ConsideraServicoCalculoValorTotalFatura) {
        this.ConsideraServicoCalculoValorTotalFatura = ConsideraServicoCalculoValorTotalFatura;
    }

    public String getCobraServicoVinculadoQuandoAguaEsgotoZerados() {
        return CobraServicoVinculadoQuandoAguaEsgotoZerados;
    }

    public void setCobraServicoVinculadoQuandoAguaEsgotoZerados(String CobraServicoVinculadoQuandoAguaEsgotoZerados) {
        this.CobraServicoVinculadoQuandoAguaEsgotoZerados = CobraServicoVinculadoQuandoAguaEsgotoZerados;
    }

    public String getNomeArquivoExportacao() {
        return NomeArquivoExportacao;
    }

    public void setNomeArquivoExportacao(String NomeArquivoExportacao) {
        this.NomeArquivoExportacao = NomeArquivoExportacao;
    }

    public Double getValorMaximoAcrescimoDesconto() {
        return ValorMaximoAcrescimoDesconto;
    }

    public void setValorMaximoAcrescimoDesconto(Double ValorMaximoAcrescimoDesconto) {
        this.ValorMaximoAcrescimoDesconto = ValorMaximoAcrescimoDesconto;
    }

    public String getUtilizaDescontoParaCobrancaValorMinimoFatura() {
        return UtilizaDescontoParaCobrancaValorMinimoFatura;
    }

    public void setUtilizaDescontoParaCobrancaValorMinimoFatura(String UtilizaDescontoParaCobrancaValorMinimoFatura) {
        this.UtilizaDescontoParaCobrancaValorMinimoFatura = UtilizaDescontoParaCobrancaValorMinimoFatura;
    }

    public Long getTipoServicoImposto() {
        return TipoServicoImposto;
    }

    public void setTipoServicoImposto(Long TipoServicoImposto) {
        this.TipoServicoImposto = TipoServicoImposto;
    }

    public Long getIdentificador() {
        return Identificador;
    }

    public void setIdentificador(Long Identificador) {
        this.Identificador = Identificador;
    }

    public String getServicoAdicionadoRotinaCalculo() {
        return ServicoAdicionadoRotinaCalculo;
    }

    public void setServicoAdicionadoRotinaCalculo(String ServicoAdicionadoRotinaCalculo) {
        this.ServicoAdicionadoRotinaCalculo = ServicoAdicionadoRotinaCalculo;
    }

    public Long getServicoSequencial() {
        return ServicoSequencial;
    }

    public void setServicoSequencial(Long ServicoSequencial) {
        this.ServicoSequencial = ServicoSequencial;
    }

    public String getDesconsideraCobrancaQuandoConsumoMenorTarifaMinima() {
        return DesconsideraCobrancaQuandoConsumoMenorTarifaMinima;
    }

    public void setDesconsideraCobrancaQuandoConsumoMenorTarifaMinima(String DesconsideraCobrancaQuandoConsumoMenorTarifaMinima) {
        this.DesconsideraCobrancaQuandoConsumoMenorTarifaMinima = DesconsideraCobrancaQuandoConsumoMenorTarifaMinima;
    }

    public Long getConsumoLimite() {
        return ConsumoLimite;
    }

    public void setConsumoLimite(Long ConsumoLimite) {
        this.ConsumoLimite = ConsumoLimite;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
